### ISSUE TITLE
Suggestion: Right Margin CSS

### ISSUE THREAD

**Issue by Rannddy** [mashirochan/Mashiro-chan#9]
One thing that I don't see in a lot of themes, right margin customization. Something like this:
[![Screenshot from Gyazo](https://gyazo.com/18c705271d412f0d8461ddf36ef918d5/raw)](https://gyazo.com/18c705271d412f0d8461ddf36ef918d5)

**Comment by mashirochan** [comment]
I like Discord's default members list actually, thanks for the suggestion though!
